const data = [
    {
      id  : '1',
      question:"What is text summarization, and how does your tool work?",
      answer:
        "Text summarization is the process of condensing large amounts of text into shorter versions while retaining the key information. Our tool utilizes advanced algorithms to analyze the input text and extract the most important sentences or paragraphs, generating a concise summary automatically.",
    },
    {
      id  : '2',
      question: " Can I customize the summaries generated by your tool?",
      answer:
        "Yes, our tool offers customization options to tailor the summaries according to your specific requirements. You can adjust parameters such as the length of the summary and the level of detail to suit your preferences.",
    },
    {
      id  : '3',
      question: " How accurate are the summaries generated by your tool?",
      answer:
        "Our tool employs state-of-the-art natural language processing techniques to ensure high accuracy in the generated summaries. While the accuracy may vary depending on factors such as the complexity of the input text, we continuously refine and improve our algorithms to deliver reliable results.",
    },
    {
      id  : '4',
      question: " Is my data secure when using your tool?",
      answer:
        "We take data security and privacy seriously. Your data is encrypted and stored securely, and we adhere to strict confidentiality protocols to protect your information.",
    },
  ];

  export default data;